<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parking Report - <?= ucfirst($filter_by) ?></title>
    <link href="<?= base_url('assets/css/bootstrap.css') ?>" rel="stylesheet">
    <style>
        @media print {
            .no-print { display: none; }
            .page-break { page-break-after: always; }
            body { padding: 20px; }
            .table { width: 100% !important; margin-bottom: 1rem; break-inside: auto; }
            .table td, .table th { 
                background-color: #fff !important; 
                border: 1px solid #dee2e6 !important; 
            }
        }
        body { 
            font-family: Arial, sans-serif;
            background-color: #fff;
            padding: 20px;
        }
        .container { 
            max-width: 1200px; 
            margin: 0 auto; 
            background: #fff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #eee;
        }
        .system-name {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
        }
        .report-title {
            font-size: 20px;
            color: #666;
        }
        .report-info { 
            margin: 20px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 5px;
        }
        .table { margin-top: 20px; }
        .table th { 
            background-color: #f8f9fa;
            font-weight: 600;
        }
        .total-section {
            margin-top: 30px;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 5px;
        }
        .badge {
            padding: 5px 10px;
            border-radius: 3px;
            font-size: 12px;
        }
        .badge-success { background: #28a745; color: white; }
        .badge-secondary { background: #6c757d; color: white; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="system-name">Smart Parking Management System</div>
            <div class="report-title">Vehicle Parking Report</div>
        </div>
        
        <div class="report-info">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Report Type:</strong> <?= ucwords(str_replace('_', ' ', $filter_by)) ?> Report</p>
                    <p><strong>Search Value:</strong> <?= htmlspecialchars($query) ?></p>
                    <p><strong>Generated On:</strong> <?= date('F j, Y g:i A', strtotime($generation_date)) ?></p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p><strong>Generated By:</strong> <?= htmlspecialchars($current_admin->username) ?></p>
                </div>
            </div>
        </div>

        <?php if (empty($vehicles)): ?>
            <div class="alert alert-info">
                <i class="fas fa-info-circle"></i> No vehicles found matching the search criteria.
            </div>
        <?php else: ?>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Booking No</th>
                            <th>Vehicle No</th>
                            <th>Vehicle Type</th>
                            <th>Slot No</th>
                            <th>Arrival Time</th>
                            <th>Status</th>
                            <th>Charge (₹)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        $total_charge = 0;
                        $parked_count = 0;
                        foreach($vehicles as $index => $vehicle): 
                            $total_charge += $vehicle->parking_charge;
                            if ($vehicle->status == 0) $parked_count++;
                        ?>
                        <tr>
                            <td><?= $index + 1 ?></td>
                            <td><?= $vehicle->id ?></td>
                            <td><?= htmlspecialchars($vehicle->vehicle_no) ?></td>
                            <td><?= ucfirst($vehicle->vehicle_type) ?></td>
                            <td><?= $vehicle->parking_area_no ?></td>
                            <td><?= date('M j, Y g:i A', strtotime($vehicle->arrival_time)) ?></td>
                            <td>
                                <?php if ($vehicle->status == 0): ?>
                                    <span class="badge badge-success">Currently Parked</span>
                                <?php else: ?>
                                    <span class="badge badge-secondary">Left</span>
                                <?php endif; ?>
                            </td>
                            <td class="text-end">₹<?= number_format($vehicle->parking_charge, 2) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="total-section">
                <div class="row">
                    <div class="col-md-4">
                        <p><strong>Total Records:</strong> <?= count($vehicles) ?></p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>Currently Parked:</strong> <?= $parked_count ?></p>
                    </div>
                    <div class="col-md-4 text-md-end">
                        <p><strong>Total Charges:</strong> ₹<?= number_format($total_charge, 2) ?></p>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="mt-4 mb-4 text-center no-print">
            <button onclick="window.print()" class="btn btn-primary">
                <i class="fas fa-print"></i> Print Report
            </button>
            <a href="<?= base_url('admin/download_report?filter_by=' . $filter_by . '&query=' . urlencode($query)) ?>" class="btn btn-success">
                <i class="fas fa-download"></i> Download Report
            </a>
            <button onclick="window.close()" class="btn btn-secondary">
                <i class="fas fa-times"></i> Close
            </button>
        </div>

        <script>

        // Auto-close if no records found after 3 seconds
        window.onload = function() {
            if (document.querySelector('.alert-info')) {
                setTimeout(function() {
                    window.close();
                }, 3000);
            }
        };
        </script>
    </div>

    <script>
        // Auto-close if no records found after 3 seconds
        window.onload = function() {
            if (document.querySelector('.alert-info')) {
                setTimeout(function() {
                    window.close();
                }, 3000);
            }
        };
    </script>
</body>
</html>